### ISSUE TITLE
Image does not display

### ISSUE THREAD

**Issue by MrPeterJin** [mbkotori/mbkotori-s-blog#1]
This website needs to further enhance links and its corrsponding media. For instance, several images won't work like the screenshot shown below:

![image](https://user-images.githubusercontent.com/51412849/171199884-c609ad6c-49da-4330-9c23-1577cdd7d332.png)

**Comment by mbkotori** [comment]
These error pictures are stored on the old server and I deleted them. Now I migrated these images and the latex formula problem has been fixed.
